# Instructions found here: https://github.com/plexinc/pms-docker/tree/master
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Denver
      - PLEX_CLAIM=<Retrieve token from https://account.plex.tv/en/claim>
      - PLEX_UID=1000
      - PLEX_GID=1000
      # Disable hardware transcoding
      # - PLEX_DISABLE_TRANSCODER_HARDWARE_ACCELERATION=true
    network_mode: host
    volumes:
      - /opt/plex/config:/config
      - /opt/plex/transcode:/transcode
      - /mnt/plex-media:/data
    devices:
      - /dev/dri:/dev/dri